//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaCartas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticias
    {
        public int codigo { get; set; }
        public string nombre_noticia { get; set; }
        public string descripcion_noticia { get; set; }
        public string foto_noticia { get; set; }
    }
}
